### ISSUE TITLE
Remove requirement to select a party in the primary

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/v3.ksvotes.org#247]
For 2022 primary, unaffiliated voters can request a ballot for the Constitutional amendment question.

This is uncommon but could happen again, so making the requirement management via config variable would be best.

Somewhat related to BlueprintKansas/v3.ksvotes.org#253 - if we had a text field for specials then someone could use that for this.

For now, simplest thing is just to remove the requirement (or allow Unaffiliated selection to be able to move forward)

**Comment by karpet** [comment]
parties now managed via #329
