### ISSUE TITLE
Add United Kansas as a party option for new registrants

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/v3.ksvotes.org#326]
They have been certified as a party as of 5/24/24. 

Secondarily, can we make these options an editable table so that it doesn't require programming to make updates?

![image](https://github.com/ BlueprintKansas/v3.ksvotes.org/assets/30677505/0dba48b4-c66a-442a-b4d4-064cebec525b)

![image](https://github.com/BlueprintKansas/v3.ksvotes.org/assets/30677505/83ee6b96-4ad8-4090-bf22-574ca4b5000d)

**Comment by karpet** [comment]
#329 adds all parties as .txt files so they can easily be edited. There is a separate list each for AB and VR.
